apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: kubernetes-deployment-clean-cronjob
  namespace: monitoring
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: kubernetes-deployment-clean-cronjob
            image: bigbigy/kubernetes-deployment-clean-cronjob:latest
            command: ["/cleanDeployment"]
            args: ["-web_url","http://localhost:9090/api/v1/alerts"]
          restartPolicy: OnFailure
